# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DhKeys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DhKeys
  pod 'BigNumber', :git => 'https://github.com/mkrd/Swift-Big-Integer.git'

end
